### PR TITLE
Added metadata.json for Kaichat to select models

### PR DESCRIPTION
**Pull request by akashvenus**
To fix issue #22

### CODE REVIEW

**Comment by mikhailocampo** [comment]
Looks good for metadata json. I like your format and maybe we can apply the same to other projects

For now, can you update the function for Quizzify under `app/features/Quizzify/tools.py` for where we actually call the model? I think we manually create a `VertexAI` instance and pass the hardcoded `gemini-1.0-pro-002` but now that you have this on metadata use that variable instead

**Comment by akashvenus** [comment]
Done the changes. Could you please review it when you get time ? Thank you

**Review by mikhailocampo — COMMENTED** [review]
LGTM. Will perform a quick check on a docker container and then combine with two other small PRs so it is one deployment

**Comment by akashvenus** [comment]
Sure !!!

**Comment by mikhailocampo** [comment]
Since Langchain released a new way to authenticate outside of just the `VertexAI` class, we can actually use the `GoogleGenerativeAI` class and specify the model there

We will also need to have the model name definition within the metadata.json of the respective tool rather than separate file i suppose

**Pull request closed without merging**
